export const PUBLIC_KEYS = {
    DEVELOPMENT: `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCySenSi/gEPoRq6LubJTN91RrB
WHTB/dI4gIrwd1cbVB0tdDfqYFCPgKQ30QI8riu5L5uKlZ+TjAfHoZCmuxFTMk5r
zg7rwW5jO7AfabIkXWqrzzpJnURWc5w0g8hlGgInaA/iK+FRUosPuwqMLeqRbbKL
+4cP1n8iXIg0cHH/mwIDAQAB
-----END PUBLIC KEY-----`
}