export const PUBLIC_KEYS = {
    DEVELOPMENT: `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDT6dLqxNZMNaqWPDqrjK6J1Sxg
3d3waKACTVReBKxriAu6wCqWBZrMYFaSlyzqwgZUuxINVkIhDv7eIWXvHNTaMraN
g/ZXrOxhli5FijE3CdbVIqk0ctoQ+qOqOLZk7Gvq38bi7dLVKQ5mv5P2xnElZIvM
gY/+8x1/HLMfed2pWwIDAQAB
-----END PUBLIC KEY-----`,
    PRODUCTION: `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDWUkoIBL4rfpHIJ/eXSTBTw7W5
cBzAKM6e9L/wUH8FI3e3eZrYbU5ilBv/+40IevBQDPcSKjVJHEWHQia34iAyxPBs
cRm9zP7zl8Fgp8b/NvXCZ3FcbLAAvHiHgLCSIKP3raaLX9TAEb4KZMvPmEEnS3A4
M6UbW3Z6dGKrVejASwIDAQAB
-----END PUBLIC KEY-----`,
}
